<?php
/**
 * @file
 * Ting Proposed Search module logic.
 */

/**
 * Creates renderable array of suggestions.
 *
 * @param $items
 *   Suggested items.
 *
 * @return array
 */
function ting_proposed_searches_make_item_list(array $items) {
  $links = array();

  // Make a list of suggesttions.
  foreach ($items as $key => $suggest) {
    $zero_hit_link = array(
      '#theme' => 'link',
      '#path' => "search/ting/{$suggest}",
      '#weight' => 0,
      '#text' => $key,
      '#options' => array(
        'attributes' => array(
          'class' => array(
            'opensuggest-link',
          ),
        ),
        'html' => TRUE,
      ),
    );
    $links[] = drupal_render($zero_hit_link);
  }

  // Label for suggestions.
  $render['label'] = array(
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#value' => t('Did you mean:'),
    '#attributes' => array(
      'class' => array('opensuggest-label'),
    ),
    '#prefix' => '<div class="opensuggest-wrapper">',
  );

  // Render array of suggestions.
  $render['suggest_list'] = array(
    '#theme' => 'item_list',
    '#type' => 'ul',
    '#attributes' => array(
      'class' => array('links', 'opensuggest-links'),
    ),
    '#items' => $links,
    '#suffix' => '</div>',
  );

  drupal_add_css(drupal_get_path('module', 'ting_proposed_searches') . '/css/ting_proposed_searches.css');

  return $render;
}

/**
 * Implements hook_panels_pane_content_alter().
 *
 * Force insert proposed searches onto the search results page.
 */
function ting_proposed_searches_panels_pane_content_alter($content, $pane, $args, $contexts) {
  if ($pane->type == 'search_result' && $content->delta == 'result') {
    $search_result = &drupal_static('ting_search_results');

    if ($search_result->numTotalObjects == '0') {
      $search_arg = $args[0];

      module_load_include('inc', 'ting_search_autocomplete', 'includes/ting_search_autocomplete.ajax');
      $suggestions = ting_search_autocomplete_get_suggestions($search_arg);

      $items = array();
      if (!empty($suggestions)) {
        foreach ($suggestions as $k => $suggestion) {
          $items[$k] = $suggestion;
        }

        $link_items = ting_proposed_searches_make_item_list($items);

        $new_content = $content->content;
        if (!empty($link_items)) {
          $new_content .= render($link_items);
        }

        $content->content = $new_content;
      }
    }
  }
}
